# Generated by Django 2.1.2 on 2018-10-24 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('lb', models.CharField(max_length=30)),
                ('xh', models.CharField(max_length=30)),
                ('jg', models.IntegerField()),
                ('sl', models.IntegerField()),
                ('hj', models.IntegerField()),
                ('bz', models.BooleanField()),
            ],
        ),
    ]
