# Generated by Django 2.1.2 on 2018-11-19 01:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='售后单位')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='auth.Group', verbose_name='负责部门')),
            ],
            options={
                'verbose_name': '售后单位',
                'verbose_name_plural': '售后单位',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('故障描述', models.CharField(max_length=30)),
                ('价格', models.IntegerField()),
                ('数量', models.IntegerField()),
                ('教室', models.CharField(max_length=30)),
                ('报账', models.BooleanField()),
                ('方式', models.CharField(max_length=30)),
                ('状态', models.CharField(default='未通知售后', max_length=15)),
                ('通知时间', models.DateField(blank=True, null=True)),
                ('到校时间', models.DateField(blank=True, null=True)),
                ('返校时间', models.DateField(blank=True, null=True)),
                ('响应时间', models.DurationField(blank=True, null=True)),
                ('修复时间', models.DurationField(blank=True, null=True)),
                ('合计', models.IntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('售后', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer')),
            ],
            options={
                'verbose_name': '维修记录',
                'verbose_name_plural': '维修记录',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Report_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('detail', models.CharField(default='无', max_length=30, verbose_name='备注')),
                ('report_time', models.DateField(verbose_name='报账时间')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer', verbose_name='售后')),
            ],
            options={
                'verbose_name': '报账时间',
                'verbose_name_plural': '报账时间',
                'ordering': ['-report_time'],
            },
        ),
        migrations.CreateModel(
            name='Unit_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('型号', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': '设备型号',
                'verbose_name_plural': '设备型号',
            },
        ),
        migrations.CreateModel(
            name='Unit_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('设备类型', models.CharField(max_length=30)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer', verbose_name='售后单位')),
            ],
            options={
                'verbose_name': '类别',
                'verbose_name_plural': '类别',
            },
        ),
        migrations.AddField(
            model_name='unit_models',
            name='设备类型',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_types'),
        ),
        migrations.AddField(
            model_name='notes',
            name='型号',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_models'),
        ),
        migrations.AddField(
            model_name='notes',
            name='报账时间',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Report_time'),
        ),
        migrations.AddField(
            model_name='notes',
            name='类别',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_types'),
        ),
    ]
