# Generated by Django 2.1.2 on 2018-11-19 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_time',
            name='customer',
        ),
    ]
