# Generated by Django 2.1.2 on 2018-11-19 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_remove_report_time_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_time',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer', verbose_name='售后'),
            preserve_default=False,
        ),
    ]
