# Generated by Django 2.1.2 on 2018-10-24 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181024_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='js',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
