# Generated by Django 2.1.2 on 2018-10-24 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_notes_js'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='hj',
            new_name='价格',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='jg',
            new_name='合计',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='lb',
            new_name='型号',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='sl',
            new_name='序号',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='bz',
            new_name='报账',
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='xh',
            new_name='教室',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='js',
        ),
        migrations.AddField(
            model_name='notes',
            name='数量',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='类别',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
