# Generated by Django 2.1.2 on 2018-10-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20181024_1049'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_types',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('设备型号', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='notes',
            name='型号',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='类别',
        ),
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddField(
            model_name='notes',
            name='类别型号',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_types'),
            preserve_default=False,
        ),
    ]
