# Generated by Django 2.1.2 on 2018-10-25 01:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20181025_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
