# Generated by Django 2.1.2 on 2018-10-25 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20181025_0937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='类别型号',
            new_name='类别',
        ),
        migrations.RenameField(
            model_name='unit_types',
            old_name='设备型号',
            new_name='型号',
        ),
    ]
