# Generated by Django 2.1.3 on 2018-11-27 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20181121_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='sn',
            field=models.CharField(blank=True, default='无', max_length=30, null=True, verbose_name='序列号'),
        ),
    ]
