# Generated by Django 2.1.3 on 2018-11-28 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20181127_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='scraped',
            field=models.BooleanField(default=False, verbose_name='是否报废'),
        ),
    ]
