# Generated by Django 2.1.2 on 2018-10-25 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20181025_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='类别',
        ),
    ]
