# Generated by Django 2.1.2 on 2018-10-25 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_remove_notes_类别'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='date',
        ),
    ]
