# Generated by Django 2.1.2 on 2018-10-25 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20181025_0954'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unit_models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('型号', models.CharField(max_length=30)),
            ],
        ),
        migrations.RenameField(
            model_name='notes',
            old_name='类别型号',
            new_name='类别',
        ),
        migrations.RenameField(
            model_name='unit_types',
            old_name='设备型号',
            new_name='设备类型',
        ),
        migrations.AddField(
            model_name='unit_models',
            name='设备类型',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_types'),
        ),
        migrations.AddField(
            model_name='notes',
            name='型号',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_models'),
            preserve_default=False,
        ),
    ]
