# Generated by Django 2.1.2 on 2018-10-25 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0012_auto_20181025_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='序号',
        ),
    ]
