# Generated by Django 2.1.2 on 2018-10-26 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_remove_notes_序号'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date']},
        ),
        migrations.RemoveField(
            model_name='notes',
            name='合计',
        ),
    ]
