# Generated by Django 2.1.2 on 2018-10-26 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0014_auto_20181026_0945'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date'], 'verbose_name': '维修记录'},
        ),
        migrations.AlterModelOptions(
            name='unit_models',
            options={'verbose_name': '设备型号'},
        ),
        migrations.AlterModelOptions(
            name='unit_types',
            options={'verbose_name': '类别'},
        ),
    ]
