# Generated by Django 2.1.2 on 2018-10-29 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20181026_0949'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ['-date'], 'verbose_name': '维修记录', 'verbose_name_plural': '维修记录'},
        ),
        migrations.AlterModelOptions(
            name='unit_models',
            options={'verbose_name': '设备型号', 'verbose_name_plural': '设备型号'},
        ),
        migrations.AlterModelOptions(
            name='unit_types',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AddField(
            model_name='notes',
            name='合计',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
