# Generated by Django 2.1.2 on 2018-10-31 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0016_auto_20181029_0900'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='售后单位')),
            ],
            options={
                'verbose_name': '售后单位',
                'verbose_name_plural': '售后单位',
            },
        ),
        migrations.CreateModel(
            name='Report_time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='名称')),
                ('detail', models.CharField(max_length=30, verbose_name='备注')),
                ('report_time', models.DateField(verbose_name='报账时间')),
            ],
            options={
                'verbose_name': '报账时间',
                'verbose_name_plural': '报账时间',
            },
        ),
    ]
