# Generated by Django 2.1.2 on 2018-10-31 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0017_customer_report_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='售后',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='报账时间',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Report_time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notes',
            name='方式',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
