# Generated by Django 2.1.2 on 2018-10-31 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0018_auto_20181031_0930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='报账时间',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Report_time'),
        ),
    ]
