# Generated by Django 2.1.2 on 2018-10-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0019_auto_20181031_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='report_time',
            name='test_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
