# Generated by Django 2.1.2 on 2018-11-05 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0020_report_time_test_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fault',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fault_title', models.CharField(max_length=30, verbose_name='故障描述')),
                ('fault_unit_models', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_models', verbose_name='设备型号')),
                ('fault_unit_types', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Unit_types', verbose_name='设备名称')),
            ],
            options={
                'verbose_name': '故障描述',
                'verbose_name_plural': '故障描述',
            },
        ),
        migrations.AlterModelOptions(
            name='report_time',
            options={'ordering': ['-report_time'], 'verbose_name': '报账时间', 'verbose_name_plural': '报账时间'},
        ),
    ]
