# Generated by Django 2.1.2 on 2018-11-05 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0021_auto_20181105_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='故障描述',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Fault'),
            preserve_default=False,
        ),
    ]
