# Generated by Django 2.1.2 on 2018-11-05 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0024_remove_unit_types_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit_types',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer', verbose_name='售后单位'),
            preserve_default=False,
        ),
    ]
