# Generated by Django 2.1.2 on 2018-11-11 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0027_customer_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fault',
            name='fault_unit_models',
        ),
        migrations.RemoveField(
            model_name='fault',
            name='fault_unit_types',
        ),
        migrations.AlterField(
            model_name='notes',
            name='故障描述',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='Fault',
        ),
    ]
