# Generated by Django 2.1.2 on 2018-11-11 08:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0029_auto_20181111_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='到校时间',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='返校时间',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='通知时间',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
