# Generated by Django 2.1.2 on 2018-11-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0030_auto_20181111_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='到校时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='返校时间',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notes',
            name='通知时间',
            field=models.DateField(blank=True, null=True),
        ),
    ]
