# Generated by Django 2.1.2 on 2018-11-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0031_auto_20181111_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='状态',
            field=models.CharField(default='未通知售后', max_length=15),
        ),
    ]
