# Generated by Django 2.1.2 on 2018-11-17 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0032_notes_状态'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report_time',
            name='test_time',
        ),
        migrations.AddField(
            model_name='report_time',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='notes.Customer', verbose_name='售后'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='report_time',
            name='detail',
            field=models.CharField(default='无', max_length=30, verbose_name='备注'),
        ),
    ]
