# Generated by Django 2.1.3 on 2018-11-25 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='设备名称')),
                ('ip', models.CharField(max_length=30, verbose_name='ip地址')),
                ('date', models.DateField(verbose_name='日期')),
                ('startime', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('endtime', models.DateTimeField(blank=True, null=True, verbose_name='结束时间')),
                ('used_time', models.DurationField(blank=True, null=True, verbose_name='持续时间')),
            ],
        ),
    ]
